# Generated by Django 4.1.5 on 2023-01-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('profession', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('city', models.CharField(choices=[('Purnea', 'Purnea'), ('Patna', 'Patna'), ('Kolkata', 'Kolkata'), ('Mumbai', 'Mumbai'), ('Ahmadabad', 'Ahmadabad'), ('Bengaluru', 'Bengaluru')], max_length=200)),
            ],
        ),
    ]
